### ISSUE TITLE
can't initialized Zend/http

### ISSUE THREAD

**Issue by enterume** [zendframework/zend-http#90]
in config\modules.config.php:

```php
return [
    'DoctrineModule',
    'DoctrineORMModule',
    'Zend\Http',
    'Zend\Cache',
    'Zend\Paginator',
    'Zend\I18n',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Session',
    'Zend\Mvc\Plugin\Prg',
    'Zend\Mvc\Plugin\Identity',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Mvc\Plugin\FilePrg',
    'Zend\Form',
    'Zend\Router',
    'Zend\Validator',
    'Zend\Validator',
    'Application',
];
```

But it return :

```html
<b>Fatal error</b>:  Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (Zend\Http) could not be initialized.' in /var/www/html/zf3/blog/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:203
Stack trace:
#0 /var/www/html/zf3/blog/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(175): Zend\ModuleManager\ModuleManager-&gt;loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/www/html/zf3/blog/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager-&gt;loadModule('Zend\\Http')
#2 /var/www/html/zf3/blog/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\ModuleManager\ModuleManager-&gt;onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/html/zf3/blog/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager-&gt;triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#4 /var/www/html/zf3/blog/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(120):  in <b>/var/www/html/zf3/blog/vendor/zendframework/zend-modulemanager/src/ModuleManager.php</b> on line <b>203</b>
```

Any idea?

**Comment by Ocramius** [comment]
Zend\Http is not a module ;-)

**Comment by froschdesign** [comment]
@enterume 
Remove `Zend\Http` from the module.config.php file and use the class directly:
```php
$request = new \Zend\Http\Request();
```
See also the [quick start in documentation](https://docs.zendframework.com/zend-http/request/#quick-start).
